packages:
  - apps/*
  - services/*
  - packages/*
allowBuilds:
  '@prisma/engines': set this to true or false
  '@scarf/scarf': false
  esbuild: set this to true or false
  prisma: true
  sharp: true
  unrs-resolver: false
  '@prisma/engines@7.8.0': true
  'esbuild@0.28.1': true
